"""Build and install the macOS menu bar app as a proper ``.app`` bundle.

Two things make a macOS 26 status item actually render, and both are easy to
get wrong:

1. **The bundle must have a real identity.** ``NSBundle.mainBundle()`` resolves
   from the *main executable's* path. A launcher that ``exec``s an interpreter
   living outside the bundle leaves the process with ``bundleIdentifier() ==
   None``, and macOS then never assigns it a menu bar slot — the icon is
   registered but invisible, with no error anywhere.
2. **The menu bar must have room.** A full menu bar parks new items off-screen.

So this installer copies the interpreter *into* ``Contents/MacOS/`` and points
the launcher at that copy. The Python source stays in the repository, so editing
it takes effect on the next launch — no rebuild step to forget.

```text
python3 hooks/install_macos_app.py              # build, install, launch
python3 hooks/install_macos_app.py --uninstall  # remove it again
python3 hooks/install_macos_app.py --print-only # show what would be written
```
"""

from __future__ import annotations

import argparse
import os
import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parents[1]
MENUBAR_SCRIPT = PLUGIN_ROOT / "scripts" / "headroom_menubar.py"
DEFAULT_APP = Path.home() / "Applications" / "headroom.app"
BUNDLE_ID = "dev.headroom.menubar"
LOG_PATH = Path.home() / ".headroom" / "logs" / "menubar.log"

#: A dedicated venv keeps PyObjC out of the hook's own interpreter.
DESKTOP_PYTHON = Path.home() / ".headroom" / "venv" / "bin" / "python"

INFO_PLIST = {
    "CFBundleName": "headroom",
    "CFBundleDisplayName": "headroom",
    "CFBundleIdentifier": BUNDLE_ID,
    "CFBundleExecutable": "headroom",
    "CFBundleVersion": "1",
    "CFBundleShortVersionString": "0.1.0",
    "CFBundlePackageType": "APPL",
    "LSMinimumSystemVersion": "13.0",
    # No Dock icon, no main menu: a pure menu bar accessory.
    "LSUIElement": True,
    # Keep the ten-second refresh alive when nothing else is happening.
    "NSAppSleepDisabled": True,
    "NSSupportsAutomaticTermination": False,
}


def real_interpreter(venv_python: Path) -> Path:
    """The actual binary behind a venv's ``bin/python`` symlink."""
    return Path(os.path.realpath(venv_python))


def version_dir(interpreter: Path) -> str:
    """``python3.13`` — the lib directory name the interpreter expects."""
    name = interpreter.name
    if name.startswith("python") and "." in name:
        return f"python{'.'.join(name[len('python'):].split('.')[:2])}"
    return f"python{sys.version_info.major}.{sys.version_info.minor}"


def launcher_script(log_path: Path, script: Path, title_mode: str) -> str:
    return (
        "#!/bin/sh\n"
        "# Generated by headroom's install_macos_app.py.\n"
        '# The interpreter lives beside this script, inside the bundle: that is\n'
        "# what gives the process a bundle identity and therefore a menu bar slot.\n"
        'here=$(cd "$(dirname "$0")" && pwd)\n'
        f'exec "$here/python" "{script}" --log "{log_path}" '
        f"--title-mode {title_mode} \"$@\"\n"
    )


def build(app_path: Path, venv_python: Path, script: Path, log_path: Path,
          title_mode: str = "text") -> dict:
    contents = app_path / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"
    for directory in (macos, resources):
        directory.mkdir(parents=True, exist_ok=True)

    interpreter = real_interpreter(venv_python)
    if not interpreter.is_file():
        raise FileNotFoundError(f"cannot resolve {venv_python} -> {interpreter}")
    base = interpreter.parent.parent
    libdir = contents / "lib"
    libdir.mkdir(exist_ok=True)

    # 1. The interpreter itself, inside the bundle.
    bundled = macos / "python"
    shutil.copy2(interpreter, bundled)

    # 2. Its shared library, which the copied binary finds via @rpath.
    copied = []
    for dylib in sorted((base / "lib").glob("libpython*.dylib")):
        shutil.copy2(dylib, libdir / dylib.name)
        copied.append(dylib.name)

    # 3. pyvenv.cfg so the copy still finds the stdlib next to its original home.
    #    It goes one level above MacOS/: codesign requires everything inside
    #    Contents/MacOS to be signed code, and Python looks in the parent too.
    (contents / "pyvenv.cfg").write_text(
        f"home = {interpreter.parent}\ninclude-system-site-packages = false\n",
        encoding="utf-8")

    # 4. The desktop venv's packages, linked in at the location sys.prefix implies.
    #    Prefer the venv's own site-packages: that is where PyObjC lives.
    packages = libdir / version_dir(interpreter) / "site-packages"
    packages.parent.mkdir(parents=True, exist_ok=True)
    candidates = (
        venv_python.parent.parent / "lib" / version_dir(interpreter) / "site-packages",
        Path(os.path.realpath(venv_python)).parent.parent / "lib" / version_dir(interpreter)
        / "site-packages",
    )
    venv_packages = next((path for path in candidates if path.is_dir()), None)
    if venv_packages is None:
        raise FileNotFoundError(f"no site-packages beside {venv_python}")
    if packages.is_symlink() or packages.exists():
        packages.unlink()
    packages.symlink_to(venv_packages)

    # 5. The launcher that ties it together.
    launcher = macos / "headroom"
    launcher.write_text(launcher_script(log_path, script, title_mode), encoding="utf-8")
    launcher.chmod(0o755)

    (contents / "Info.plist").write_bytes(plistlib.dumps(INFO_PLIST))
    return {"app": app_path, "launcher": launcher, "interpreter": interpreter,
            "dylibs": copied, "packages": venv_packages}


def sign(app_path: Path) -> tuple[bool, str]:
    """Ad-hoc signature, inside out. Local use only; Gatekeeper allows own builds.

    ``--deep`` is avoided: it walks non-code files (``pyvenv.cfg``) and refuses
    to sign the bundle as a result.
    """
    codesign = shutil.which("codesign") or "/usr/bin/codesign"
    contents = app_path / "Contents"
    nested = sorted((contents / "lib").glob("*.dylib"))
    nested += [contents / "MacOS" / "python"]
    for target in [*nested, app_path]:
        if not target.exists():
            continue
        try:
            result = subprocess.run([codesign, "-s", "-", "--force", str(target)],
                                    capture_output=True, timeout=60, check=False)
        except (OSError, subprocess.TimeoutExpired) as exc:
            return False, f"{type(exc).__name__}: {exc}"
        if result.returncode:
            return False, result.stderr.decode("utf-8", "replace").strip()
    return True, f"ad-hoc ({len(nested)} nested + bundle)"


def launch(app_path: Path) -> tuple[bool, str]:
    try:
        result = subprocess.run(["open", str(app_path)], capture_output=True,
                                timeout=15, check=False)
    except (OSError, subprocess.TimeoutExpired) as exc:
        return False, f"{type(exc).__name__}: {exc}"
    if result.returncode:
        return False, result.stderr.decode("utf-8", "replace").strip()
    return True, "opened"


def uninstall(app_path: Path) -> None:
    """Quit any running copy, then remove the bundle."""
    subprocess.run(["pkill", "-f", "headroom_menubar.py"], capture_output=True, check=False)
    shutil.rmtree(app_path, ignore_errors=True)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--app", type=Path, default=DEFAULT_APP,
                        help="where to build the bundle; default ~/Applications/headroom.app")
    parser.add_argument("--python", type=Path, default=DESKTOP_PYTHON,
                        help="venv interpreter that has PyObjC; "
                             "default ~/.headroom/venv/bin/python")
    parser.add_argument("--log", type=Path, default=LOG_PATH)
    parser.add_argument("--title-mode", choices=("icon", "text", "both"), default="text",
                        help="text shows the percent (default); icon is a ~22pt ring, "
                             "roughly half the width, for a crowded menu bar")
    parser.add_argument("--uninstall", action="store_true")
    parser.add_argument("--print-only", action="store_true",
                        help="describe the bundle without writing it")
    parser.add_argument("--no-launch", action="store_true")
    args = parser.parse_args(argv)

    if sys.platform != "darwin":
        parser.error("the menu bar app is macOS only")
    if args.uninstall:
        uninstall(args.app)
        print(f"removed {args.app}")
        return 0
    if not MENUBAR_SCRIPT.is_file():
        parser.error(f"missing {MENUBAR_SCRIPT}")
    if not args.python.is_file():
        parser.error(f"{args.python} does not exist; create it with:\n"
                     f"  python3 -m venv {args.python.parent.parent}\n"
                     f"  {args.python.parent}/pip install -r "
                     f"{PLUGIN_ROOT / 'requirements-desktop.txt'}")
    interpreter = real_interpreter(args.python)
    if args.print_only:
        print(f"app        : {args.app}")
        print(f"bundle id  : {BUNDLE_ID}")
        print(f"interpreter: {args.python} -> {interpreter}")
        print(f"copies in  : {args.app / 'Contents' / 'MacOS' / 'python'}")
        print(f"launcher   : {args.app / 'Contents' / 'MacOS' / 'headroom'}")
        print(f"runs       : {interpreter} {MENUBAR_SCRIPT} --log {args.log} "
              f"--title-mode {args.title_mode}")
        return 0

    # Replace rather than merge: a stale bundle pointing at a moved checkout is
    # the most likely way this breaks after the repository moves.
    if args.app.exists():
        uninstall(args.app)
    built = build(args.app, args.python, MENUBAR_SCRIPT, args.log, args.title_mode)
    print(f"built   {built['app']}")
    print(f"copied  {built['interpreter'].name} + {len(built['dylibs'])} dylib(s) "
          f"+ site-packages link")
    ok, detail = sign(args.app)
    print(f"{'signed' if ok else 'sign failed'}: {detail}")
    if not args.no_launch:
        ok, detail = launch(args.app)
        print(f"{'launched' if ok else 'launch failed'}: {detail}")
        print(f"log: {args.log}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
